top_modules:
  # - fastq_screen:
  #     name: "FastQ Screen"
  #     info: "FastQ Screen results with the raw data."
  #     path_filters:
  #       - "*fastq_screen.txt"
  - fastqc:
      name: "Raw FastQC"
      anchor: "fastqc_raw"
      info: "FastQC results for the raw data."
      path_filters:
        - "*raw_fastqc*_fastqc.zip"
  - fastqc:
      name: "Fastp FastQC"
      anchor: "fastqc_fastp"
      info: "FastQC for the fastp processed data."
      path_filters:
        - "*fastp_fastqc*_fastqc.zip"
  - kallisto:
      name: "Kallisto"
      anchor: "kallisto"
      info: "Kallisto pseudoalignment results."
      path_filters:
        - "*kallisto.log"
  - samtools/stats:
      name: "Samtools Stats"
      anchor: "samtools"
      info: " Samtools alignment results."
      path_filters:
        - "*pseudoalignments_stats.txt"
        - "*pseudoalignments_flagstat.txt"